# -*- coding: utf-8 -*-
"""data_EDA_project3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yiKt2ZN67UWiHNO8oPLHLOTLfrPhZgj2
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('/content/heart.csv')

print("Dataset Shape:", data.shape)
print("\nColumns:")
print(data.columns.tolist())

print("Dataset Information:")
data.info()

print("\nMissing values")
print(data.isnull().sum())

duplicate_count = data.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

data = data.drop_duplicates().reset_index(drop=True)

print("Dataset Shape after removing duplicates:", data.shape)
print("Duplicate rows remaining:", data.duplicated().sum())

data.describe().T

numeric_columns = ['age', 'trestbps', 'chol', 'thalach', 'oldpeak']

plt.figure(figsize=(12, 8))

for i, column in enumerate(numeric_columns, 1):
    plt.subplot(2, 3, i)
    sns.boxplot(y=data[column])
    plt.title(column)

plt.tight_layout()
plt.show()

from sklearn.preprocessing import StandardScaler

clinical_columns = [
    'age',
    'trestbps',
    'chol',
    'thalach',
    'oldpeak'
]

scaler = StandardScaler()

data_scaled = data.copy()

data_scaled[clinical_columns] = scaler.fit_transform(
    data_scaled[clinical_columns]
)

print(data_scaled[clinical_columns].head())

target_counts = data['target'].value_counts()

print("Heart Disease Distribution:")
print(target_counts)

print("\nPercentage Distribution:")
print((data['target'].value_counts(normalize=True) * 100).round(2))

average_age = data['age'].mean()

print("Average age of patients:", round(average_age, 2), "years")

gender_counts = data['sex'].value_counts()

print("Gender Distribution:")
print(gender_counts)

print("\nGender Percentage:")
print((data['sex'].value_counts(normalize=True) * 100).round(2))

average_bp = data['trestbps'].mean()

print("Average resting blood pressure:", round(average_bp, 2), "mm Hg")

fbs_high = (data['fbs'] == 1).sum()

print("Number of patients with fasting blood sugar >120 mg/dl:", fbs_high)

chest_pain_counts = data['cp'].value_counts().sort_index()

print("Chest Pain Type Distribution:")
print(chest_pain_counts)

max_heart_rate = data['thalach'].max()

print("Maximum heart rate achieved:", max_heart_rate, "bpm")

exang_percentage = (data['exang'] == 1).mean() * 100

print("Percentage with exercise-induced angina:", round(exang_percentage, 2), "%")

average_cholesterol = data['chol'].mean()

print("Average cholesterol:", round(average_cholesterol, 2), "mg/dl")

restecg_2_count = (data['restecg'] == 2).sum()

print("Number of patients with restecg = 2:", restecg_2_count)

ca_distribution = data['ca'].value_counts().sort_index()

print("Distribution of ca:")
print(ca_distribution)

correlation = data['age'].corr(data['chol'])

print("Correlation between age and cholesterol:", round(correlation, 3))

data['age_group'] = pd.cut(
    data['age'],
    bins=[20, 40, 50, 60, 70, 80],
    labels=['21-40', '41-50', '51-60', '61-70', '71-80'],
    include_lowest=True
)

chest_pain_age = pd.crosstab(data['age_group'], data['cp'])

print("Chest Pain Distribution Across Age Groups:")
print(chest_pain_age)

heart_rate_by_angina = data.groupby('exang')['thalach'].mean()

print("Average Maximum Heart Rate by Exercise-Induced Angina:")
print(heart_rate_by_angina.round(2))

bp_by_sex = data.groupby('sex')['trestbps'].mean()

print("Average Resting Blood Pressure by Sex:")
print(bp_by_sex.round(2))

from scipy.stats import ttest_ind

female_bp = data.loc[data['sex'] == 0, 'trestbps']
male_bp = data.loc[data['sex'] == 1, 'trestbps']

t_stat, p_value = ttest_ind(female_bp, male_bp, equal_var=False)

print("T-statistic:", round(t_stat, 3))
print("P-value:", round(p_value, 4))

fbs_heart_disease = data.groupby('fbs')['target'].mean() * 100

print("Heart Disease Rate by Fasting Blood Sugar:")
print(fbs_heart_disease.round(2))

ca_heart_disease = data.groupby('ca')['target'].mean() * 100

print("Heart Disease Rate by Number of Major Vessels:")
print(ca_heart_disease.round(2))

oldpeak_by_cp = data.groupby('cp')['oldpeak'].mean()

print("Average Oldpeak by Chest Pain Type:")
print(oldpeak_by_cp.round(2))

thal_heart_disease = data[data['target'] == 1]['thal'].value_counts().sort_index()

print("Thalassemia Distribution Among Heart Disease Patients:")
print(thal_heart_disease)

print("\nPercentage Distribution:")
print((thal_heart_disease / thal_heart_disease.sum() * 100).round(2))

heart_patients = data[data['target'] == 1].copy()

heart_patients['age_group'] = pd.cut(
    heart_patients['age'],
    bins=[20, 40, 50, 60, 70, 80],
    labels=['21-40', '41-50', '51-60', '61-70', '71-80'],
    include_lowest=True
)

risk_combinations = (
    heart_patients
    .groupby(['age_group', 'cp', 'exang', 'fbs'], observed=True)
    .size()
    .sort_values(ascending=False)
)

print("Most Common Risk-Factor Combinations Among Heart Disease Patients:")
print(risk_combinations.head(10))

clinical_comparison = data.groupby('target')[
    ['age', 'trestbps', 'chol', 'thalach', 'oldpeak']
].mean()

print("Average Clinical Measurements by Heart Disease Status:")
print(clinical_comparison.round(2))

from sklearn.linear_model import LogisticRegression

X = data[['age', 'chol', 'trestbps']]
y = data['target']

model = LogisticRegression()
model.fit(X, y)

print("Logistic Regression Model trained successfully.")

coefficients = pd.DataFrame({
    'Variable': X.columns,
    'Coefficient': model.coef_[0]
})

print("Logistic Regression Coefficients:")
print(coefficients)

accuracy = model.score(X, y)

print("Model Accuracy:", round(accuracy * 100, 2), "%")

clinical_columns = ['age', 'trestbps', 'chol', 'thalach', 'oldpeak']

correlations = data[clinical_columns + ['target']].corr()['target'].drop('target')

print("Correlation with Heart Disease:")
print(correlations.sort_values(ascending=False).round(3))

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X_all = data.drop(columns=['target', 'age_group'], errors='ignore')
y_all = data['target']

X_train, X_test, y_train, y_test = train_test_split(
    X_all,
    y_all,
    test_size=0.2,
    random_state=42,
    stratify=y_all
)

print("Training rows:", X_train.shape[0])
print("Testing rows:", X_test.shape[0])

model_all = LogisticRegression(max_iter=1000)

model_all.fit(X_train, y_train)

print("Logistic Regression model trained successfully.")

from sklearn.metrics import accuracy_score

y_pred = model_all.predict(X_test)

accuracy_all = accuracy_score(y_test, y_pred)

print("Test Accuracy:", round(accuracy_all * 100, 2), "%")

from sklearn.metrics import classification_report

print("Classification Report:")
print(classification_report(y_test, y_pred))

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

plt.figure(figsize=(6, 4))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=['Predicted 0', 'Predicted 1'],
    yticklabels=['Actual 0', 'Actual 1']
)

plt.xlabel("Prediction")
plt.ylabel("Actual")
plt.title("Confusion Matrix - Logistic Regression")
plt.show()

tn, fp, fn, tp = cm.ravel()

print("True Negatives (TN):", tn)
print("False Positives (FP):", fp)
print("False Negatives (FN):", fn)
print("True Positives (TP):", tp)

coefficients_all = pd.DataFrame({
    'Feature': X_all.columns,
    'Coefficient': model_all.coef_[0]
})

coefficients_all = coefficients_all.sort_values(
    by='Coefficient',
    ascending=False
)

print("Logistic Regression Coefficients:")
print(coefficients_all)

coefficients_all['Absolute_Coefficient'] = coefficients_all['Coefficient'].abs()

print(
    coefficients_all[
        ['Feature', 'Coefficient', 'Absolute_Coefficient']
    ].sort_values(
        by='Absolute_Coefficient',
        ascending=False
    )
)

from sklearn.metrics import roc_auc_score

y_prob = model_all.predict_proba(X_test)[:, 1]

auc_score = roc_auc_score(y_test, y_prob)

print("ROC-AUC Score:", round(auc_score, 3))

from sklearn.metrics import roc_curve
import matplotlib.pyplot as plt

fpr, tpr, thresholds = roc_curve(y_test, y_prob)

plt.figure(figsize=(7, 5))
plt.plot(fpr, tpr, label=f'Logistic Regression (AUC = {auc_score:.3f})')
plt.plot([0, 1], [0, 1], linestyle='--')

plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve - Logistic Regression')
plt.legend()
plt.grid()
plt.show()

print("Advanced Q3 - Logistic Regression Summary")
print("-" * 45)

print("Training Rows:", len(X_train))
print("Testing Rows:", len(X_test))
print("Test Accuracy:", round(accuracy_all * 100, 2), "%")
print("ROC-AUC:", round(auc_score, 3))

print("\nConfusion Matrix:")
print(cm)

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

slope_cp = pd.crosstab(data['cp'], data['slope'])

print("Slope Distribution Across Chest Pain Types:")
print(slope_cp)

slope_cp_percent = pd.crosstab(
    data['cp'],
    data['slope'],
    normalize='index'
) * 100

print("Slope Distribution Across Chest Pain Types (%):")
print(slope_cp_percent.round(2))

slope_cp_percent.plot(
    kind='bar',
    stacked=True,
    figsize=(8, 5)
)

plt.xlabel('Chest Pain Type')
plt.ylabel('Percentage (%)')
plt.title('Slope Distribution Across Chest Pain Types')
plt.legend(title='Slope')
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

from scipy.stats import chi2_contingency

chi2, p_value, dof, expected = chi2_contingency(slope_cp)

print("Chi-square statistic:", round(chi2, 3))
print("P-value:", round(p_value, 4))
print("Degrees of freedom:", dof)

print("Advanced Q4 - Slope Distribution Across Chest Pain Types")
print("-" * 55)

print("\nPercentage Distribution:")
print(slope_cp_percent.round(2))

print("\nChi-square statistic:", round(chi2, 3))
print("P-value:", round(p_value, 4))
print("Degrees of freedom:", dof)

if p_value < 0.05:
    print("\nConclusion: There is a statistically significant association between")
    print("chest pain type and slope.")
else:
    print("\nConclusion: No statistically significant association was found.")

thal_outcome = data.groupby('thal')['target'].agg(
    ['count', 'sum', 'mean']
)

thal_outcome['Outcome_Rate_%'] = thal_outcome['mean'] * 100

print("Outcome Rate by Thalassemia Type:")
print(thal_outcome.round(2))

plt.figure(figsize=(7, 5))

plt.bar(
    thal_outcome.index.astype(str),
    thal_outcome['Outcome_Rate_%']
)

plt.xlabel('Thalassemia Type')
plt.ylabel('Target = 1 Rate (%)')
plt.title('Heart Disease Outcome Rate by Thalassemia Type')
plt.ylim(0, 100)

plt.tight_layout()
plt.show()

thal_target_table = pd.crosstab(data['thal'], data['target'])

print("Thalassemia vs Heart Disease:")
print(thal_target_table)

chi2_thal, p_thal, dof_thal, expected_thal = chi2_contingency(
    thal_target_table
)

print("\nChi-square statistic:", round(chi2_thal, 3))
print("P-value:", round(p_thal, 4))
print("Degrees of freedom:", dof_thal)

print("Advanced Q5 - Thalassemia and Heart Disease Outcome")
print("-" * 55)

print("\nOutcome Rate by Thalassemia Type:")
print(thal_outcome[['count', 'sum', 'Outcome_Rate_%']].round(2))

print("\nChi-square statistic:", round(chi2_thal, 3))
print("P-value:", round(p_thal, 4))
print("Degrees of freedom:", dof_thal)

print("\nConclusion:")
print("There is a statistically significant association between")
print("thalassemia type and heart disease outcome in this dataset.")
print("A true survival-rate analysis cannot be performed because")
print("the dataset does not contain survival time or follow-up information.")

