# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hUy6nOJa8CcYqxXYDuZ7rjxU5WLc7qNd
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/googleplaystore.csv')

df.head()

df.shape

df.info()

df.columns

df.describe(include='all')

df.isnull().sum()

df[df['Rating'].isnull()].head()

df[df['Rating'].isnull()].shape

df[df['Type'].isnull()]

df[df['Content Rating'].isnull()]

df[df['Current Ver'].isnull()]

df[df['Android Ver'].isnull()]

df['Rating'].median()

df['Rating']=df['Rating'].fillna(df['Rating'].median())

df['Rating'].isnull().sum()

df[df['Type'].isnull()]

df['Type']=df['Type'].fillna(df['Type'].mode()[0])

df['Type'].isnull().sum()

df['Content Rating']=df['Content Rating'].fillna(df['Content Rating'].mode()[0])

df['Content Rating'].isnull().sum()

df['Current Ver'] = df['Current Ver'].fillna(df['Current Ver'].mode()[0])

df['Current Ver'].isnull().sum()

df['Android Ver'] = df['Android Ver'].fillna(df['Android Ver'].mode()[0])

df['Android Ver'].isnull().sum()

df.isnull().sum()

df.duplicated().sum()

df['App'].duplicated().sum()

df[df['App'].duplicated(keep=False)].sort_values('App').head(20)

df = df.drop_duplicates()

df.duplicated().sum()

df.shape

df = df.drop_duplicates()

print("Duplicate rows:", df.duplicated().sum())
print("Dataset shape:", df.shape)

df['Installs'].dtype

df['Installs'].head(10)

df[df['Installs'] == 'Free']

(df['Installs'] == 'Free').sum()

df = df.drop(index=10472)

df = df.reset_index(drop=True)

df['Installs'] = df['Installs'].str.replace(',', '', regex=False)
df['Installs'] = df['Installs'].str.replace('+', '', regex=False)
df['Installs'] = pd.to_numeric(df['Installs'])

print("Installs data type:", df['Installs'].dtype)
print("Missing Installs:", df['Installs'].isnull().sum())

df['Installs'].head()

df['Price'].head(10)

df['Price'].dtype

df['Price'] = df['Price'].str.replace('$', '', regex=False)

df['Price'] = pd.to_numeric(df['Price'])

print("Price data type:", df['Price'].dtype)
print("Missing Price:", df['Price'].isnull().sum())

df['Price'].head()

df['Last Updated'] = pd.to_datetime(df['Last Updated'])

print("Last Updated data type:", df['Last Updated'].dtype)
print("Missing Last Updated:", df['Last Updated'].isnull().sum())

df['Last Updated'].head()

df['Update_Year'] = df['Last Updated'].dt.year

df[['Last Updated', 'Update_Year']].head()

df['Update_Year'].value_counts().sort_index()

df['Size'].value_counts().head(20)

df['Size'].dtype

(df['Size'] == 'Varies with device').sum()

def convert_size(size):
    if size == 'Varies with device':
        return np.nan
    elif size.endswith('M'):
        return float(size.replace('M', ''))
    elif size.endswith('k'):
        return float(size.replace('k', '')) / 1024
    else:
        return np.nan

df['Size_MB'] = df['Size'].apply(convert_size)

df[['Size', 'Size_MB']].head(10)

print("Missing Size_MB:", df['Size_MB'].isnull().sum())

df.info()

df.isnull().sum()

df.shape

average_rating = df['Rating'].mean()
print("Average App Rating:", average_rating)

print("Highest Rating:", df['Rating'].max())
print("Lowest Rating:", df['Rating'].min())
print("Median Rating:", df['Rating'].median())

df['Rating'].describe()

plt.figure(figsize=(10, 6))

plt.hist(df['Rating'], bins=20)

plt.title('Distribution of App Ratings')
plt.xlabel('Rating')
plt.ylabel('Number of Apps')

plt.tight_layout()
plt.show()

top_rated_apps = df[['App', 'Rating', 'Reviews']].sort_values(
    by=['Rating', 'Reviews'],
    ascending=[False, False]
).head(10)

top_rated_apps

top_reviewed_apps = df[['App', 'Rating', 'Reviews']].sort_values(
    by='Reviews',
    ascending=False
).head(10)

top_reviewed_apps

category_counts = df['Category'].value_counts()

category_counts

plt.figure(figsize=(12, 8))

category_counts.sort_values().plot(kind='barh')

plt.title('Number of Apps by Category')
plt.xlabel('Number of Apps')
plt.ylabel('Category')

plt.tight_layout()
plt.show()

category_rating = df.groupby('Category')['Rating'].mean().sort_values(ascending=False)

category_rating

plt.figure(figsize=(12, 8))

category_rating.sort_values().plot(kind='barh')

plt.title('Average Rating by Category')
plt.xlabel('Average Rating')
plt.ylabel('Category')

plt.tight_layout()
plt.show()

type_counts = df['Type'].value_counts()

type_counts

plt.figure(figsize=(7, 5))

type_counts.plot(kind='bar')

plt.title('Free vs Paid Apps')
plt.xlabel('App Type')
plt.ylabel('Number of Apps')
plt.xticks(rotation=0)

plt.tight_layout()
plt.show()

type_rating = df.groupby('Type')['Rating'].mean()

type_rating

top_installed_apps = df[['App', 'Installs', 'Rating', 'Reviews']].sort_values(
    by='Installs',
    ascending=False
).head(10)

top_installed_apps

top_reviewed_apps = df[['App', 'Reviews', 'Rating', 'Installs']].sort_values(
    by='Reviews',
    ascending=False
).head(10)

top_reviewed_apps

df['Reviews'].describe()

df['Reviews'] = pd.to_numeric(df['Reviews'], errors='coerce')

print("Reviews data type:", df['Reviews'].dtype)
print("Missing Reviews:", df['Reviews'].isnull().sum())

reviews_stats = df['Reviews'].describe()

reviews_stats

plt.figure(figsize=(10, 6))

plt.hist(df['Reviews'], bins=50)

plt.xscale('log')

plt.title('Distribution of App Reviews')
plt.xlabel('Number of Reviews (log scale)')
plt.ylabel('Number of Apps')

plt.tight_layout()
plt.show()

paid_apps = df[df['Type'] == 'Paid']

paid_apps['Price'].describe()

plt.figure(figsize=(10, 6))

plt.hist(paid_apps['Price'], bins=30)

plt.title('Price Distribution of Paid Apps')
plt.xlabel('Price ($)')
plt.ylabel('Number of Apps')

plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))

plt.scatter(paid_apps['Price'], paid_apps['Rating'], alpha=0.5)

plt.title('Price vs Rating of Paid Apps')
plt.xlabel('Price ($)')
plt.ylabel('Rating')

plt.tight_layout()
plt.show()

price_rating_corr = paid_apps['Price'].corr(paid_apps['Rating'])

print("Correlation between Price and Rating:", price_rating_corr)

paid_apps['Price_Range'] = pd.cut(
    paid_apps['Price'],
    bins=[0, 5, 10, 25, 50, 100, 500],
    labels=['$0–5', '$5–10', '$10–25', '$25–50', '$50–100', '$100+']
)

price_range_rating = paid_apps.groupby('Price_Range', observed=True)['Rating'].mean()

price_range_rating

price_range_count = paid_apps['Price_Range'].value_counts().sort_index()

price_range_count

plt.figure(figsize=(10, 6))

price_range_count.plot(kind='bar')

plt.title('Number of Paid Apps by Price Range')
plt.xlabel('Price Range')
plt.ylabel('Number of Apps')
plt.xticks(rotation=0)

plt.tight_layout()
plt.show()

content_rating_counts = df['Content Rating'].value_counts()

content_rating_counts

plt.figure(figsize=(9, 6))

content_rating_counts.plot(kind='bar')

plt.title('Distribution of Apps by Content Rating')
plt.xlabel('Content Rating')
plt.ylabel('Number of Apps')
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

content_rating_avg = df.groupby('Content Rating')['Rating'].mean().sort_values(ascending=False)

content_rating_avg

plt.figure(figsize=(10, 6))

content_rating_avg.plot(kind='bar')

plt.title('Average Rating by Content Rating')
plt.xlabel('Content Rating')
plt.ylabel('Average Rating')
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

genre_counts = df['Genres'].value_counts().head(15)

genre_counts

plt.figure(figsize=(12, 7))

genre_counts.sort_values().plot(kind='barh')

plt.title('Top 15 App Genres by Number of Apps')
plt.xlabel('Number of Apps')
plt.ylabel('Genre')

plt.tight_layout()
plt.show()

genre_rating = df.groupby('Genres')['Rating'].mean().sort_values(ascending=False).head(15)

genre_rating

genre_summary = df.groupby('Genres').agg(
    App_Count=('App', 'count'),
    Average_Rating=('Rating', 'mean')
).sort_values(by='Average_Rating', ascending=False).head(15)

genre_summary

genre_summary_reliable = df.groupby('Genres').agg(
    App_Count=('App', 'count'),
    Average_Rating=('Rating', 'mean')
)

genre_summary_reliable = genre_summary_reliable[
    genre_summary_reliable['App_Count'] >= 10
].sort_values(by='Average_Rating', ascending=False).head(15)

genre_summary_reliable

plt.figure(figsize=(12, 7))

genre_summary_reliable['Average_Rating'].sort_values().plot(kind='barh')

plt.title('Average Rating by Genre (Minimum 10 Apps)')
plt.xlabel('Average Rating')
plt.ylabel('Genre')

plt.tight_layout()
plt.show()

year_counts = df['Update_Year'].value_counts().sort_index()

year_counts

plt.figure(figsize=(10, 6))

year_counts.plot(kind='line', marker='o')

plt.title('Number of Apps Updated by Year')
plt.xlabel('Update Year')
plt.ylabel('Number of Apps')
plt.grid(True)

plt.tight_layout()
plt.show()

year_rating = df.groupby('Update_Year')['Rating'].mean()

year_rating

plt.figure(figsize=(10, 6))

year_rating.plot(kind='line', marker='o')

plt.title('Average App Rating by Update Year')
plt.xlabel('Update Year')
plt.ylabel('Average Rating')
plt.grid(True)

plt.tight_layout()
plt.show()

size_stats = df['Size_MB'].describe()

size_stats

plt.figure(figsize=(10, 6))

plt.hist(df['Size_MB'].dropna(), bins=30)

plt.title('Distribution of App Sizes')
plt.xlabel('App Size (MB)')
plt.ylabel('Number of Apps')

plt.tight_layout()
plt.show()

size_by_type = df.groupby('Type')['Size_MB'].mean()

size_by_type

plt.figure(figsize=(8, 6))

size_by_type.plot(kind='bar')

plt.title('Average App Size: Free vs Paid')
plt.xlabel('App Type')
plt.ylabel('Average Size (MB)')
plt.xticks(rotation=0)

plt.tight_layout()
plt.show()

size_rating_data = df[['Size_MB', 'Rating']].dropna()

plt.figure(figsize=(10, 6))

plt.scatter(
    size_rating_data['Size_MB'],
    size_rating_data['Rating'],
    alpha=0.4
)

plt.title('App Size vs Rating')
plt.xlabel('App Size (MB)')
plt.ylabel('Rating')

plt.tight_layout()
plt.show()

size_rating_corr = df['Size_MB'].corr(df['Rating'])

print("Correlation between App Size and Rating:", size_rating_corr)

size_installs_corr = df['Size_MB'].corr(df['Installs'])

print("Correlation between App Size and Installs:", size_installs_corr)

reviews_rating_corr = df['Reviews'].corr(df['Rating'])

print("Correlation between Reviews and Rating:", reviews_rating_corr)

reviews_installs_corr = df['Reviews'].corr(df['Installs'])

print("Correlation between Reviews and Installs:", reviews_installs_corr)

plt.figure(figsize=(10, 6))

plt.scatter(
    df['Installs'],
    df['Reviews'],
    alpha=0.4
)

plt.xscale('log')
plt.yscale('log')

plt.title('Reviews vs Installs')
plt.xlabel('Number of Installs (log scale)')
plt.ylabel('Number of Reviews (log scale)')

plt.tight_layout()
plt.show()

numeric_cols = [
    'Rating',
    'Reviews',
    'Installs',
    'Price',
    'Size_MB',
    'Update_Year'
]

correlation_matrix = df[numeric_cols].corr()

correlation_matrix

top_reviewed_apps = df[['App', 'Reviews', 'Installs', 'Rating']].sort_values(
    by='Reviews',
    ascending=False
).head(10)

top_reviewed_apps

category_installs = df.groupby('Category')['Installs'].mean().sort_values(ascending=False)

category_installs

plt.figure(figsize=(12, 8))

category_installs.sort_values().plot(kind='barh')

plt.title('Average Installs by App Category')
plt.xlabel('Average Installs')
plt.ylabel('Category')

plt.tight_layout()
plt.show()

category_reviews = df.groupby('Category')['Reviews'].mean().sort_values(ascending=False)

category_reviews

plt.figure(figsize=(12, 8))

category_reviews.sort_values().plot(kind='barh')

plt.title('Average Reviews by App Category')
plt.xlabel('Average Reviews')
plt.ylabel('Category')

plt.tight_layout()
plt.show()

type_installs = df.groupby('Type')['Installs'].mean()

type_installs

plt.figure(figsize=(8, 6))

type_installs.plot(kind='bar')

plt.title('Average Installs: Free vs Paid Apps')
plt.xlabel('App Type')
plt.ylabel('Average Installs')
plt.xticks(rotation=0)

plt.tight_layout()
plt.show()

type_reviews = df.groupby('Type')['Reviews'].mean()

type_reviews

plt.figure(figsize=(8, 6))

type_reviews.plot(kind='bar')

plt.title('Average Reviews: Free vs Paid Apps')
plt.xlabel('App Type')
plt.ylabel('Average Reviews')
plt.xticks(rotation=0)

plt.tight_layout()
plt.show()

most_expensive_apps = df[['App', 'Price', 'Rating', 'Reviews', 'Installs']].sort_values(
    by='Price',
    ascending=False
).head(10)

most_expensive_apps

price_installs_corr = paid_apps['Price'].corr(paid_apps['Installs'])

print("Correlation between Price and Installs:", price_installs_corr)

price_range_installs = paid_apps.groupby('Price_Range', observed=True)['Installs'].mean()

price_range_installs

plt.figure(figsize=(10, 6))

price_range_installs.plot(kind='bar')

plt.title('Average Installs by Price Range')
plt.xlabel('Price Range')
plt.ylabel('Average Installs')
plt.xticks(rotation=0)

plt.tight_layout()
plt.show()

price_range_reviews = paid_apps.groupby(
    'Price_Range', observed=True
)['Reviews'].mean()

price_range_reviews

plt.figure(figsize=(10, 6))

price_range_reviews.plot(kind='bar')

plt.title('Average Reviews by Price Range')
plt.xlabel('Price Range')
plt.ylabel('Average Reviews')
plt.xticks(rotation=0)

plt.tight_layout()
plt.show()

price_range_count = paid_apps['Price_Range'].value_counts().sort_index()

price_range_count

price_range_summary = pd.DataFrame({
    'App_Count': price_range_count,
    'Average_Reviews': price_range_reviews,
    'Average_Installs': price_range_installs
})

price_range_summary

category_summary = df.groupby('Category').agg(
    App_Count=('App', 'count'),
    Average_Rating=('Rating', 'mean'),
    Average_Installs=('Installs', 'mean'),
    Average_Reviews=('Reviews', 'mean')
).sort_values(by='Average_Installs', ascending=False)

category_summary.head(10)

plt.figure(figsize=(12, 8))

category_summary['Average_Installs'].sort_values().plot(kind='barh')

plt.title('Average Installs by App Category')
plt.xlabel('Average Installs')
plt.ylabel('Category')

plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 8))

category_summary['Average_Reviews'].sort_values().plot(kind='barh')

plt.title('Average Reviews by App Category')
plt.xlabel('Average Reviews')
plt.ylabel('Category')

plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))

plt.scatter(
    category_summary['Average_Installs'],
    category_summary['Average_Rating'],
    alpha=0.7
)

plt.xscale('log')

plt.title('Average Installs vs Average Rating by Category')
plt.xlabel('Average Installs (log scale)')
plt.ylabel('Average Rating')

plt.tight_layout()
plt.show()

category_installs_rating_corr = category_summary['Average_Installs'].corr(
    category_summary['Average_Rating']
)

print("Correlation between Average Installs and Average Rating by Category:",
      category_installs_rating_corr)

category_reviews_installs_corr = category_summary['Average_Reviews'].corr(
    category_summary['Average_Installs']
)

print(
    "Correlation between Average Reviews and Average Installs by Category:",
    category_reviews_installs_corr
)

plt.figure(figsize=(10, 6))

plt.scatter(
    category_summary['Average_Installs'],
    category_summary['Average_Reviews'],
    alpha=0.7
)

plt.xscale('log')
plt.yscale('log')

plt.title('Average Installs vs Average Reviews by Category')
plt.xlabel('Average Installs (log scale)')
plt.ylabel('Average Reviews (log scale)')

plt.tight_layout()
plt.show()

category_type = pd.crosstab(
    df['Category'],
    df['Type']
)

category_type.head(10)

paid_percentage = (
    category_type['Paid'] /
    category_type.sum(axis=1)
) * 100

paid_percentage.sort_values(ascending=False)

plt.figure(figsize=(12, 8))

paid_percentage.sort_values().plot(kind='barh')

plt.title('Percentage of Paid Apps by Category')
plt.xlabel('Paid Apps (%)')
plt.ylabel('Category')

plt.tight_layout()
plt.show()

category_type_rating = df.pivot_table(
    index='Category',
    columns='Type',
    values='Rating',
    aggfunc='mean'
)

category_type_rating

free_rating = df[df['Type'] == 'Free']['Rating'].mean()
paid_rating = df[df['Type'] == 'Paid']['Rating'].mean()

rating_difference = paid_rating - free_rating

print("Average Free App Rating:", free_rating)
print("Average Paid App Rating:", paid_rating)
print("Difference:", rating_difference)

rating_by_type = df.groupby('Type')['Rating'].mean()

plt.figure(figsize=(8, 6))

rating_by_type.plot(kind='bar')

plt.title('Average Rating: Free vs Paid Apps')
plt.xlabel('App Type')
plt.ylabel('Average Rating')
plt.xticks(rotation=0)

plt.tight_layout()
plt.show()

content_rating_installs = df.groupby(
    'Content Rating'
)['Installs'].mean().sort_values(ascending=False)

content_rating_installs

plt.figure(figsize=(10, 6))

content_rating_installs.plot(kind='bar')

plt.title('Average Installs by Content Rating')
plt.xlabel('Content Rating')
plt.ylabel('Average Installs')

plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

content_rating_reviews = df.groupby(
    'Content Rating'
)['Reviews'].mean().sort_values(ascending=False)

content_rating_reviews

plt.figure(figsize=(10, 6))

content_rating_reviews.plot(kind='bar')

plt.title('Average Reviews by Content Rating')
plt.xlabel('Content Rating')
plt.ylabel('Average Reviews')

plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 7))

sns.heatmap(
    correlation_matrix,
    annot=True,
    cmap='coolwarm',
    fmt='.2f'
)

plt.title('Correlation Matrix of Numeric Variables')
plt.tight_layout()
plt.show()

top_quality_apps = df[
    ['App', 'Rating', 'Reviews', 'Installs', 'Category']
].sort_values(
    by=['Rating', 'Reviews'],
    ascending=[False, False]
).head(10)

top_quality_apps

most_popular_apps = df[
    ['App', 'Installs', 'Reviews', 'Rating', 'Category']
].sort_values(
    by=['Installs', 'Reviews'],
    ascending=[False, False]
).head(10)

most_popular_apps

category_summary = df.groupby('Category').agg(
    App_Count=('App', 'count'),
    Average_Rating=('Rating', 'mean'),
    Average_Installs=('Installs', 'mean'),
    Average_Reviews=('Reviews', 'mean')
).sort_values(
    by='Average_Rating',
    ascending=False
)

category_summary.head(10)

category_rating = category_summary['Average_Rating'].sort_values(ascending=False)

plt.figure(figsize=(12, 8))

category_rating.plot(kind='bar')

plt.title('Average Rating by Category')
plt.xlabel('Category')
plt.ylabel('Average Rating')

plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

top_install_categories = category_summary.sort_values(
    by='Average_Installs',
    ascending=False
).head(10)

top_install_categories[['App_Count', 'Average_Rating', 'Average_Installs', 'Average_Reviews']]

plt.figure(figsize=(12, 7))

top_install_categories['Average_Installs'].sort_values().plot(kind='barh')

plt.title('Top 10 Categories by Average Installs')
plt.xlabel('Average Installs')
plt.ylabel('Category')

plt.tight_layout()
plt.show()

top_review_categories = category_summary.sort_values(
    by='Average_Reviews',
    ascending=False
).head(10)

top_review_categories[
    ['App_Count', 'Average_Rating', 'Average_Installs', 'Average_Reviews']
]

plt.figure(figsize=(12, 7))

top_review_categories['Average_Reviews'].sort_values().plot(kind='barh')

plt.title('Top 10 Categories by Average Reviews')
plt.xlabel('Average Reviews')
plt.ylabel('Category')

plt.tight_layout()
plt.show()

free_installs = df[df['Type'] == 'Free']['Installs'].mean()
paid_installs = df[df['Type'] == 'Paid']['Installs'].mean()

install_difference = free_installs - paid_installs

print("Average Free App Installs:", free_installs)
print("Average Paid App Installs:", paid_installs)
print("Difference:", install_difference)

type_installs = df.groupby('Type')['Installs'].mean()

plt.figure(figsize=(8, 6))

type_installs.plot(kind='bar')

plt.title('Average Installs: Free vs Paid Apps')
plt.xlabel('App Type')
plt.ylabel('Average Installs')
plt.xticks(rotation=0)

plt.tight_layout()
plt.show()

free_reviews = df[df['Type'] == 'Free']['Reviews'].mean()
paid_reviews = df[df['Type'] == 'Paid']['Reviews'].mean()

review_difference = free_reviews - paid_reviews

print("Average Free App Reviews:", free_reviews)
print("Average Paid App Reviews:", paid_reviews)
print("Difference:", review_difference)

type_reviews = df.groupby('Type')['Reviews'].mean()

plt.figure(figsize=(8, 6))

type_reviews.plot(kind='bar')

plt.title('Average Reviews: Free vs Paid Apps')
plt.xlabel('App Type')
plt.ylabel('Average Reviews')
plt.xticks(rotation=0)

plt.tight_layout()
plt.show()

apps_by_year = df['Update_Year'].value_counts().sort_index()

apps_by_year

plt.figure(figsize=(10, 6))

apps_by_year.plot(kind='line', marker='o')

plt.title('Number of Apps Updated by Year')
plt.xlabel('Update Year')
plt.ylabel('Number of Apps')
plt.grid(True)

plt.tight_layout()
plt.show()

installs_by_year = df.groupby('Update_Year')['Installs'].mean()

print(installs_by_year)

plt.figure(figsize=(10, 6))

installs_by_year.plot(kind='line', marker='o')

plt.title('Average Installs by Update Year')
plt.xlabel('Update Year')
plt.ylabel('Average Installs')
plt.grid(True)

plt.tight_layout()
plt.show()

reviews_by_year = df.groupby('Update_Year')['Reviews'].mean()

print(reviews_by_year)

plt.figure(figsize=(10, 6))

reviews_by_year.plot(kind='line', marker='o')

plt.title('Average Reviews by Update Year')
plt.xlabel('Update Year')
plt.ylabel('Average Reviews')
plt.grid(True)

plt.tight_layout()
plt.show()

rating_by_year = df.groupby('Update_Year')['Rating'].mean()

print(rating_by_year)

plt.figure(figsize=(10, 6))

rating_by_year.plot(kind='line', marker='o')

plt.title('Average App Rating by Update Year')
plt.xlabel('Update Year')
plt.ylabel('Average Rating')
plt.grid(True)

plt.tight_layout()
plt.show()

year_rating_corr = df['Update_Year'].corr(df['Rating'])

print("Correlation between Update Year and Rating:", year_rating_corr)

rating_type_year = df.pivot_table(
    index='Update_Year',
    columns='Type',
    values='Rating',
    aggfunc='mean'
)

print(rating_type_year)

plt.figure(figsize=(10, 6))

rating_type_year.plot(kind='line', marker='o')

plt.title('Average Rating by Update Year: Free vs Paid Apps')
plt.xlabel('Update Year')
plt.ylabel('Average Rating')
plt.grid(True)

plt.tight_layout()
plt.show()

installs_type_year = df.pivot_table(
    index='Update_Year',
    columns='Type',
    values='Installs',
    aggfunc='mean'
)

print(installs_type_year)

plt.figure(figsize=(10, 6))

installs_type_year.plot(kind='line', marker='o')

plt.title('Average Installs by Update Year: Free vs Paid Apps')
plt.xlabel('Update Year')
plt.ylabel('Average Installs')
plt.grid(True)

plt.tight_layout()
plt.show()

reviews_type_year = df.pivot_table(
    index='Update_Year',
    columns='Type',
    values='Reviews',
    aggfunc='mean'
)

print(reviews_type_year)

plt.figure(figsize=(10, 6))

reviews_type_year.plot(kind='line', marker='o')

plt.title('Average Reviews by Update Year: Free vs Paid Apps')
plt.xlabel('Update Year')
plt.ylabel('Average Reviews')
plt.grid(True)

plt.tight_layout()
plt.show()

year_summary = df.groupby('Update_Year').agg(
    App_Count=('App', 'count'),
    Average_Rating=('Rating', 'mean'),
    Average_Installs=('Installs', 'mean'),
    Average_Reviews=('Reviews', 'mean')
)

print(year_summary)

year_summary.to_csv('/content/year_summary.csv')
print("Year summary saved successfully!")

print("Final dataset shape:", df.shape)
print("\nMissing values:")
print(df.isnull().sum())

print("===== FINAL PROJECT INSIGHTS =====")

print("\n1. Overall Average Rating:")
print(round(df['Rating'].mean(), 2))

print("\n2. Most Common Category:")
print(df['Category'].value_counts().idxmax())

print("\n3. Most Common App Type:")
print(df['Type'].value_counts().idxmax())

print("\n4. Free Apps Percentage:")
print(round((df['Type'] == 'Free').mean() * 100, 2), "%")

print("\n5. Paid Apps Percentage:")
print(round((df['Type'] == 'Paid').mean() * 100, 2), "%")

print("\n6. Category with Highest Average Rating:")
print(category_summary['Average_Rating'].idxmax())

print("\n7. Category with Highest Average Installs:")
print(category_summary['Average_Installs'].idxmax())

print("\n8. Category with Highest Average Reviews:")
print(category_summary['Average_Reviews'].idxmax())

print("\n9. Year with Most Apps Updated:")
print(year_summary['App_Count'].idxmax())

print("\n10. Year with Highest Average Installs:")
print(year_summary['Average_Installs'].idxmax())

print("\n11. Year with Highest Average Reviews:")
print(year_summary['Average_Reviews'].idxmax())

print("\n12. Year with Highest Average Rating:")
print(year_summary['Average_Rating'].idxmax())

df.to_csv('/content/googleplaystore_cleaned.csv', index=False)

print("Final cleaned dataset saved successfully!")
print("Rows:", len(df))
print("Columns:", len(df.columns))

category_summary.to_csv('/content/category_summary.csv')

print("Category summary saved successfully!")

type_summary = df.groupby('Type').agg(
    App_Count=('App', 'count'),
    Average_Rating=('Rating', 'mean'),
    Average_Installs=('Installs', 'mean'),
    Average_Reviews=('Reviews', 'mean'),
    Average_Price=('Price', 'mean')
)

type_summary

type_summary.to_csv('/content/free_vs_paid_summary.csv')

print("Free vs Paid summary saved successfully!")

correlation_matrix.to_csv('/content/correlation_matrix.csv')

print("Correlation matrix saved successfully!")

final_summary = pd.DataFrame({
    'Metric': [
        'Total Apps',
        'Average Rating',
        'Free Apps %',
        'Paid Apps %',
        'Most Common Category',
        'Highest Rated Category',
        'Highest Install Category',
        'Highest Review Category',
        'Most Updated Year'
    ],
    'Value': [
        len(df),
        round(df['Rating'].mean(), 2),
        round((df['Type'] == 'Free').mean() * 100, 2),
        round((df['Type'] == 'Paid').mean() * 100, 2),
        df['Category'].value_counts().idxmax(),
        category_summary['Average_Rating'].idxmax(),
        category_summary['Average_Installs'].idxmax(),
        category_summary['Average_Reviews'].idxmax(),
        year_summary['App_Count'].idxmax()
    ]
})

final_summary

final_summary.to_csv('/content/final_project_summary.csv', index=False)

print("Final project summary saved successfully!")

import os
import shutil

project_folder = '/content/Google_Play_Store_Project'
os.makedirs(project_folder, exist_ok=True)

files_to_save = [
    'googleplaystore_cleaned.csv',
    'category_summary.csv',
    'year_summary.csv',
    'free_vs_paid_summary.csv',
    'correlation_matrix.csv',
    'final_project_summary.csv'
]

for file in files_to_save:
    source = '/content/' + file
    destination = project_folder + '/' + file

    if os.path.exists(source):
        shutil.copy(source, destination)

print("Project folder created successfully!")
print("Files in folder:")
print(os.listdir(project_folder))

readme_text = """
# Google Play Store Apps Data Analysis

## Project Overview

This project analyzes Google Play Store app data to understand app ratings,
categories, pricing, installs, reviews, content ratings, genres, and update patterns.

## Dataset

The dataset contains Google Play Store application information.

After data cleaning and preprocessing:
- Total records: 10,357
- Total columns: 16

## Tools and Technologies

- Python
- Pandas
- NumPy
- Matplotlib
- Seaborn
- Google Colab

## Data Cleaning

The following preprocessing steps were performed:
- Handled missing values
- Removed exact duplicate records
- Removed one malformed record
- Converted Installs into numeric format
- Converted Price into numeric format
- Converted Last Updated into datetime format
- Extracted Update Year
- Converted app Size into MB
- Checked the final dataset for missing values

## Analysis Performed

- Rating analysis
- Category analysis
- Free vs Paid app analysis
- Install analysis
- Review analysis
- Price analysis
- Content Rating analysis
- Genre analysis
- Yearly update analysis
- Correlation analysis
- Popular and highly rated app analysis

## Key Findings

- Overall average rating: 4.20
- FAMILY is the most common category.
- 92.61% of apps are Free.
- 7.39% of apps are Paid.
- EVENTS has the highest average rating.
- COMMUNICATION has the highest average installs.
- SOCIAL has the highest average reviews.
- 2018 has the largest number of app records.
- Reviews and installs have a strong positive correlation.

## Conclusion

The analysis provides insights into app popularity, ratings, pricing,
user engagement, categories, and update patterns in the Google Play Store dataset.

The results can help understand how different app categories and pricing
types are represented in the dataset and how installs and reviews are related.
"""

with open('/content/Google_Play_Store_Project/README.txt', 'w') as f:
    f.write(readme_text)

print("README created successfully!")

import shutil

zip_path = shutil.make_archive(
    '/content/Google_Play_Store_Project',
    'zip',
    '/content/Google_Play_Store_Project'
)

print("ZIP file created successfully!")
print(zip_path)

