# -*- coding: utf-8 -*-
"""data_EDA_project2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Epgdld7R9H2ojCWaYhJrxr8R6bgCf_Pj
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv('/content/hotel_bookings.csv')

print("Dataset loaded successfully!")
print("Shape:", df.shape)
print("\nFirst 5 rows:")
display(df.head())

print("Dataset Information")
df.info()

print("\nMissing Values:")
print(df.isnull().sum())

duplicate_count=df.duplicated().sum()
print("Number of duplicate rows:",duplicate_count)

df=df.drop_duplicates().reset_index(drop=True)
print("Duplicates removed successfully!")
print("New dataset shape:",df.shape)
print("Remaining duplicate rows:",df.duplicated().sum())

missing_values=df.isnull().sum()
print("Missing values after duplicate removal:")
print(missing_values[missing_values>0])

df['children']=df['children'].fillna(0)
print("Missing children values:",df['children'].isnull().sum())

df['country']=df['country'].fillna('unknown')
print("Missing country values:",df['country'].isnull().sum())

df['agent']=df['agent'].fillna(0)
print("Missing agent values:",df['agent'].isnull().sum())

df['company']=df['company'].fillna(0)
print("Missing company values:",df['company'].isnull().sum())

missing_values=df.isnull().sum()
print("Remaining missing values:")
print(missing_values[missing_values>0])

df['reservation_status_date']=pd.to_datetime(
    df['reservation_status_date'],
    errors='coerce'
)

print("Data type:",df['reservation_status_date'].dtype)
print("Missing dates:",df['reservation_status_date'].isnull().sum())

# Create a proper arrival date column
df['arrival_date'] = pd.to_datetime(
    df['arrival_date_year'].astype(str) + '-' +
    df['arrival_date_month'] + '-' +
    df['arrival_date_day_of_month'].astype(str),
    errors='coerce'
)

print("Arrival date created successfully!")
print("Data type:", df['arrival_date'].dtype)
print("Missing arrival dates:", df['arrival_date'].isnull().sum())

print("\nSample arrival dates:")
print(df['arrival_date'].head())

# Final data cleaning check
print("Final dataset shape:", df.shape)
print("Duplicate rows:", df.duplicated().sum())
print("Total missing values:", df.isnull().sum().sum())

print("\nData types:")
print(df.dtypes)

# Distribution of bookings by hotel type

hotel_bookings = df['hotel'].value_counts()

print("Bookings by Hotel Type:")
print(hotel_bookings)

# Plot bookings by hotel type

plt.figure(figsize=(8, 5))

hotel_bookings.plot(kind='bar')

plt.title('Distribution of Bookings by Hotel Type')
plt.xlabel('Hotel Type')
plt.ylabel('Number of Bookings')
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

# Calculate percentage of bookings by hotel type

hotel_percentage = df['hotel'].value_counts(normalize=True) * 100

print("Booking Percentage by Hotel Type:")
print(hotel_percentage.round(2))

# Count bookings by arrival month

month_order = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'
]

monthly_bookings = df['arrival_date_month'].value_counts().reindex(month_order)

print("Bookings by Arrival Month:")
print(monthly_bookings)

# Plot bookings by arrival month

plt.figure(figsize=(12, 6))

monthly_bookings.plot(kind='bar')

plt.title('Distribution of Bookings by Arrival Month')
plt.xlabel('Arrival Month')
plt.ylabel('Number of Bookings')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Find the month with the highest number of bookings

most_common_month = monthly_bookings.idxmax()
highest_booking_count = monthly_bookings.max()

print("Most Common Arrival Month:", most_common_month)
print("Number of Bookings:", highest_booking_count)

# Calculate number of canceled bookings

canceled_bookings = (df['is_canceled'] == 1).sum()

print("Number of Canceled Bookings:", canceled_bookings)

# Calculate overall cancellation rate

cancellation_rate = df['is_canceled'].mean() * 100

print("Overall Cancellation Rate:", round(cancellation_rate, 2), "%")

# Calculate average booking lead time

average_lead_time = df['lead_time'].mean()

print("Average Booking Lead Time:", round(average_lead_time, 2), "days")

# Calculate average special requests per booking

average_special_requests = df['total_of_special_requests'].mean()

print(
    "Average Special Requests per Booking:",
    round(average_special_requests, 2)
)

# Count bookings by country

country_bookings = df['country'].value_counts()

print("Top 10 Countries by Number of Bookings:")
print(country_bookings.head(10))

# Find the country with the highest number of bookings

top_country = country_bookings.idxmax()
top_country_bookings = country_bookings.max()

print("Country with Highest Bookings:", top_country)
print("Number of Bookings:", top_country_bookings)

# Calculate average ADR by hotel type

average_adr_hotel = df.groupby('hotel')['adr'].mean()

print("Average ADR by Hotel Type:")
print(average_adr_hotel.round(2))

# Calculate percentage of bookings requiring parking

parking_bookings = (df['required_car_parking_spaces'] > 0).sum()

parking_percentage = (parking_bookings / len(df)) * 100

print("Bookings Requiring Parking:", parking_bookings)
print("Percentage Requiring Parking:", round(parking_percentage, 2), "%")

# Calculate average stay duration

average_weekend_nights = df['stays_in_weekend_nights'].mean()
average_week_nights = df['stays_in_week_nights'].mean()

# Total nights for each booking
df['total_stay_nights'] = (
    df['stays_in_weekend_nights'] +
    df['stays_in_week_nights']
)

average_total_stay = df['total_stay_nights'].mean()

print("Average Weekend Nights:", round(average_weekend_nights, 2))
print("Average Week Nights:", round(average_week_nights, 2))
print("Average Total Stay:", round(average_total_stay, 2), "nights")

# Calculate bookings made through travel agents

travel_agent_bookings = (df['agent'] > 0).sum()
travel_agent_percentage = travel_agent_bookings / len(df) * 100

print("Bookings Made Through Travel Agents:", travel_agent_bookings)
print("Percentage of Bookings Through Travel Agents:", round(travel_agent_percentage, 2), "%")

# Calculate cancellation rate for each hotel type

hotel_cancellation_rate = (
    df.groupby('hotel')['is_canceled']
    .mean() * 100
)

print(hotel_cancellation_rate.round(2))

# Calculate average ADR for each market segment

adr_by_segment = (
    df.groupby('market_segment')['adr']
    .mean()
    .sort_values(ascending=False)
)

print(adr_by_segment.round(2))

# Create lead-time groups

df['lead_time_group'] = pd.cut(
    df['lead_time'],
    bins=[-1, 7, 30, 90, 180, 365, float('inf')],
    labels=[
        '0-7 days',
        '8-30 days',
        '31-90 days',
        '91-180 days',
        '181-365 days',
        '365+ days'
    ]
)

# Calculate cancellation rate for each lead-time group

lead_time_cancellation = (
    df.groupby('lead_time_group', observed=True)['is_canceled']
    .mean() * 100
)

print(lead_time_cancellation.round(2))

# Count bookings by distribution channel

distribution_counts = df['distribution_channel'].value_counts()

print(distribution_counts)

# Calculate average previous cancellations by hotel type

previous_cancellations_by_hotel = (
    df.groupby('hotel')['previous_cancellations']
    .mean()
)

print(previous_cancellations_by_hotel.round(2))

# Calculate average ADR for each year

adr_by_year = (
    df.groupby('arrival_date_year')['adr']
    .mean()
)

print(adr_by_year.round(2))

# Calculate estimated revenue
# Revenue proxy = ADR × total stay nights

df['estimated_revenue'] = df['adr'] * df['total_stay_nights']

monthly_revenue = (
    df.groupby('arrival_date_month')['estimated_revenue']
    .sum()
    .reindex(month_order)
)

print(monthly_revenue.round(2))

# Calculate average ADR based on number of special requests

adr_by_special_requests = (
    df.groupby('total_of_special_requests')['adr']
    .mean()
)

print(adr_by_special_requests.round(2))

# Calculate average stay duration for repeated vs new guests

stay_by_guest_type = (
    df.groupby('is_repeated_guest')['total_stay_nights']
    .mean()
)

print(stay_by_guest_type.round(2))

# Count bookings by reserved room type

room_type_bookings = (
    df['reserved_room_type']
    .value_counts()
)

print(room_type_bookings)

# Check the main variables for logistic regression

print(df[['is_canceled', 'lead_time', 'adr',
          'previous_cancellations',
          'booking_changes',
          'total_of_special_requests',
          'is_repeated_guest']].describe())

# Select variables for logistic regression

X = df[
    [
        'lead_time',
        'adr',
        'previous_cancellations',
        'booking_changes',
        'total_of_special_requests',
        'is_repeated_guest'
    ]
]

y = df['is_canceled']

print("X shape:", X.shape)
print("y shape:", y.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

from sklearn.linear_model import LogisticRegression

# Create the logistic regression model
logistic_model = LogisticRegression(max_iter=1000)

# Train the model
logistic_model.fit(X_train, y_train)

print("Logistic Regression model trained successfully!")

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Make predictions on the testing data
y_pred = logistic_model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Model Accuracy:", round(accuracy * 100, 2), "%")

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Examine logistic regression coefficients

coefficients = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': logistic_model.coef_[0]
})

coefficients['Absolute_Coefficient'] = coefficients['Coefficient'].abs()

coefficients = coefficients.sort_values(
    'Absolute_Coefficient',
    ascending=False
)

print(coefficients)

import statsmodels.api as sm

X_sm = sm.add_constant(X)

logit_model = sm.Logit(y, X_sm)
result = logit_model.fit()

print(result.summary())

print(df[['adr', 'adults', 'children', 'babies']].describe())

# Select variables for multiple regression

X_adr = df[['adults', 'children', 'babies']]
y_adr = df['adr']

print("X shape:", X_adr.shape)
print("y shape:", y_adr.shape)

from sklearn.linear_model import LinearRegression

# Create and train the multiple regression model
adr_model = LinearRegression()

adr_model.fit(X_adr, y_adr)

print("Multiple Regression model trained successfully!")

# Display regression coefficients

adr_coefficients = pd.DataFrame({
    'Feature': X_adr.columns,
    'Coefficient': adr_model.coef_
})

print(adr_coefficients)

print("\nIntercept:", adr_model.intercept_)

from sklearn.metrics import r2_score, mean_squared_error

# Predict ADR
adr_pred = adr_model.predict(X_adr)

# Calculate R-squared and RMSE
r2 = r2_score(y_adr, adr_pred)
rmse = mean_squared_error(y_adr, adr_pred) ** 0.5

print("R-squared:", round(r2, 4))
print("RMSE:", round(rmse, 2))

import statsmodels.api as sm

X_adr_sm = sm.add_constant(X_adr)

adr_regression = sm.OLS(y_adr, X_adr_sm).fit()

print(adr_regression.summary())

print(df[['booking_changes', 'total_of_special_requests']].describe())

correlation = df['booking_changes'].corr(
    df['total_of_special_requests']
)

print("Correlation between booking changes and special requests:",
      round(correlation, 4))

from scipy.stats import pearsonr

correlation, p_value = pearsonr(
    df['booking_changes'],
    df['total_of_special_requests']
)

print("Pearson Correlation:", round(correlation, 4))
print("P-value:", p_value)

plt.figure(figsize=(8, 5))

plt.scatter(
    df['booking_changes'],
    df['total_of_special_requests'],
    alpha=0.2
)

plt.title('Booking Changes vs Special Requests')
plt.xlabel('Number of Booking Changes')
plt.ylabel('Number of Special Requests')

plt.tight_layout()
plt.show()

monthly_cancellation = (
    df.groupby('arrival_date_month')['is_canceled']
      .mean()
      .reindex(month_order) * 100
)

print(monthly_cancellation)

plt.figure(figsize=(10, 5))

plt.plot(
    month_order,
    monthly_cancellation,
    marker='o'
)

plt.title('Monthly Cancellation Rate')
plt.xlabel('Arrival Month')
plt.ylabel('Cancellation Rate (%)')
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

highest_month = monthly_cancellation.idxmax()
highest_rate = monthly_cancellation.max()

lowest_month = monthly_cancellation.idxmin()
lowest_rate = monthly_cancellation.min()

difference = highest_rate - lowest_rate

print("Highest Cancellation Month:", highest_month)
print("Highest Cancellation Rate:", round(highest_rate, 2), "%")

print("\nLowest Cancellation Month:", lowest_month)
print("Lowest Cancellation Rate:", round(lowest_rate, 2), "%")

print("\nDifference:", round(difference, 2), "percentage points")

lead_time_by_segment = (
    df.groupby('market_segment')['lead_time']
      .mean()
      .sort_values(ascending=False)
)

print(lead_time_by_segment)

plt.figure(figsize=(12, 6))

sns.boxplot(
    data=df,
    x='market_segment',
    y='lead_time',
    showfliers=False
)

plt.title('Lead Time Distribution by Market Segment')
plt.xlabel('Market Segment')
plt.ylabel('Lead Time (Days)')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

median_lead_time = (
    df.groupby('market_segment')['lead_time']
      .median()
      .sort_values(ascending=False)
)

print(median_lead_time)

